### ISSUE TITLE
再次进入含有下拉菜单的控制器中时,点击下来菜单,程序崩溃.

### ISSUE THREAD

**Issue by tangzzz-fan** [iThinkerYZ/YZPullDownMenuDemo#2]
具体看这里的例子:https://github.com/tangzzz-fan/pullMenuTest

**Comment by akai1223** [comment]
重复监听

下拉菜单控件增加方法addObserver，removeObserver

进入含有下拉菜单的页面 增加监听
- (void) viewWillAppear:(BOOL)animated
{
    // 增加通知监听
    [_allOrderView.menu addObserver];
}

-(void) viewWillDisappear:(BOOL)animated
{
    // 移除通知监听
    [_allOrderView.menu removeObserver];
}
